baseURL = "https://teresaholfeld.com/"
languageCode = "en-us"
title = "Teresa Holfeld"
disqusShortname = "teresaholfeld"

[params]
author = "Teresa Holfeld"
intro = "Software Developer and Entrepreneur"
description = """Software developer, entrepreneur, founder of [Hamburg Coding School](https://hamburgcodingschool.com/)  
and [Small and Modern](https://smallandmodern.com/). Based in Hamburg, Germany."""
authorimage = "avatar.jpg"
dateformat = "Jan 2, 2006"
showcomments = true
    
[params.social]
github = "teresaholfeld"
xing = "Teresa_Holfeld"
linkedin = "teresa-holfeld-bb854b34"
twitter = "TeresaHolfeld"
stackoverflow = "902358/terry"
email = "teresa@smallandmodern.com"

[params.extra]
copyright = "Teresa Holfeld. [Contact/Impressum](/contact/)." 
poweredby = true

[[menu.main]]
    name = "services"
    weight = 200
    identifier = "services"
    url = "/services/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 100
    url = "/about/"
[[menu.main]]
    name = "blog"
    identifier = "blog"
    weight = 300
    url = "/blog/"
[[menu.main]]
    name = "contact"
    identifier = "contact"
    weight = 400
    url = "/contact/"

[[menu.blog]]
    name = "home"
    weight = 100
    identifier = "home"
    url = "/"
[[menu.blog]]
    name = "blog"
    identifier = "blog"
    weight = 300
    url = "/blog/"
[[menu.blog]]
    name = "contact"
    identifier = "contact"
    weight = 400
    url = "/contact/"

[markup.goldmark.renderer]
unsafe = true