baseURL = "https://teresaholfeld.com/"
languageCode = "en-us"
title = "Teresa Holfeld"

[params]
author = "Teresa Holfeld"
intro = "Software Developer and Entrepreneur"
description = "Freelance software developer, consultant, founder of [Hamburg Coding School](https://hamburgcodingschool.com/).<br/>Based in Hamburg, Germany."
authorimage = "avatar.jpg"
dateformat = "Jan 2, 2006"
    
[params.social]
github = "teresaholfeld"
xing = "Teresa_Holfeld"
linkedin = "teresa-holfeld-bb854b34"
twitter = "TeresaHolfeld"
stackoverflow = "902358/terry"
email = "teresa.holfeld@gmail.com"

[params.extra]
copyright = "Teresa Holfeld. [Contact/Impressum](/contact/)." 
poweredby = true

[[menu.main]]
    name = "services"
    weight = 200
    identifier = "services"
    url = "/services/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 100
    url = "/about/"
[[menu.main]]
    name = "contact"
    identifier = "contact"
    weight = 300
    url = "/contact/"